controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    arm_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    marge_controller:
      type: marge/Marge

arm_planning_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    constraints:
      joint_1:
        goal: 0.02
      joint_3:
        goal: 0.02
    gains:
      joint_3:
        d: 0.0
        ff_velocity_scale: 0.0
        i: 0.0
        i_clamp: 1.0
        p: 5.0

    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    interpolation_method: splines
      
gripper_group_controller:
  ros__parameters:
    joints:
      - grip_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    interpolation_method: splines

joint_state_broadcaster:
  ros__parameters:
#     extra_joints: '{}'
#     interfaces: '{}'
    joints: 
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - grip_joint
#     map_interface_to_joint_state:
#       position: position
#       velocity: velocity
#     use_local_topics: false
#     use_urdf_to_filter: true

marge_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - grip_joint

    command_interfaces:
      - home

    state_interfaces:
      - home